use crate::*;

/// Trait implemented automatically on enums data generated by strunemix.
pub trait StrunemixData<T>
where 
    Self: Sized,
    T: StrunemixName,
{
    /// Get the name of the enum value
    /// 
    /// ```rust
    /// use strunemix::*;
    /// 
    /// #[derive(Strunemix)]
    /// struct Person {
    ///   age: i32,
    ///   name: Option<String>
    /// }
    /// 
    /// let age = PersonAttrData::Age(42);
    /// 
    /// assert_eq!(age.name(), PersonAttrName::Age);
    fn name<'a>(&'a self)-> T where
        T: From<&'a Self>
    {
        T::from(self)
    }
}